### ISSUE TITLE
Record the date as part of the frontmatter on newly created docs

### ISSUE THREAD

**Issue by cjsaylor** [cjsaylor/jrnl#9]
The open command (if the entry doesn't exist) should initialize the frontmatter with a date entry.

Ex:

```yaml
---
date: 2018-07-26
---
```

the `tag` command should keep the date value unchanged and just append the tag entries:

```yaml
---
date: 2018-07-26
tags:
- sometag
```
